load("../../rare_pes/R/convert.RData")
source("../../rare_pes/R/gsa.R")
geneSetMsigdb <- getGeneSets("../db/gene_sets/MsigDB_canonical_and_hallmark_Tclin_v_6.1.0.gmt")
geneSetMsigdbEnsId <- geneset2EnsGene(geneSetMsigdb, convert_gene2EnsId)
geneSetMsigdbEnsGene <- geneset2EnsGene(geneSetMsigdb, convert_gene2EnsGene)
geneSetTclin <- getGeneSets("../db/gene_sets/Tclin_enriched_MsigDB_hallmark_canonical_TCRD_v.6.1.0.gmt")
geneSetTclinEnsId <- geneset2EnsGene(geneSetTclin, convert_gene2EnsId)
geneSetTclinEnsGene <- geneset2EnsGene(geneSetTclin, convert_gene2EnsGene)
save.image("convert.sets.RData")
